apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-nginx-azurefile
  resources:
    requests:
      storage: 1Gi
